### ISSUE TITLE
Daylight savings time clock changes are not handled

### ISSUE THREAD

**Issue by willsheppard** [waldner/croncal#1]
When the clocks go forward, the missing hour is correctly missing.

But when the clocks go back, the duplicate events are not shown, presumably because the hash key is just overwritten.

**Comment by waldner** [comment]
Makes sense. I'll have a look, thanks.

**Comment by willsheppard** [comment]
I've done some more testing and what I said was incorrect

**Comment by willsheppard** [comment]
My tests:

$ cat test.txt
0 * * * * script

# Clock changes
$ /usr/sbin/zdump -v Europe/London | grep 2016
Europe/London  Sun Mar 27 00:59:59 2016 UT = Sun Mar 27 00:59:59 2016 GMT isdst=0 gmtoff=0
Europe/London  Sun Mar 27 01:00:00 2016 UT = Sun Mar 27 02:00:00 2016 BST isdst=1 gmtoff=3600
Europe/London  Sun Oct 30 00:59:59 2016 UT = Sun Oct 30 01:59:59 2016 BST isdst=1 gmtoff=3600
Europe/London  Sun Oct 30 01:00:00 2016 UT = Sun Oct 30 01:00:00 2016 GMT isdst=0 gmtoff=0

# Forward
$ ./croncal.pl -f test.txt -s '2016-03-26 23:00' -e '2016-03-27 05:00'
2016-03-26 23:00|script
2016-03-27 00:00|script
2016-03-27 02:00|script # <-- Missed 1am as expected
2016-03-27 03:00|script
2016-03-27 04:00|script

# Back
$ ./croncal.pl -f test.txt -s '2016-10-29 23:00' -e '2016-10-30 05:00'
2016-10-29 23:00|script
2016-10-30 00:00|script
2016-10-30 01:00|script
2016-10-30 01:00|script # <-- Doubled 1am as expected
2016-10-30 02:00|script
2016-10-30 03:00|script
2016-10-30 04:00|script

**Comment by waldner** [comment]
Ah well, even better then. Thanks!
