### ISSUE TITLE
Need exactly same thing for cloud

### ISSUE THREAD

**Issue by heruwala** [waldner/croncal#4]
Hi, 

This is great, I was looking for the same thing just the difference is, I do not have Linux box and I have multiple corn jobs running on Azure cloud in the form of Azure function. how can I list them?

**Comment by waldner** [comment]
I don't have access to azure at the moment, but I suppose if you can massage/postprocess the output of the right "az funcionapp" invocation into something resembling a crontab file, then you can use that as input for croncal.
