### ISSUE TITLE
Implement day of week cycle '#' 

### ISSUE THREAD

**Issue by phibid** [waldner/croncal#5]
Could be nice to have the '#' implemented 👍 

Extract from https://en.wikipedia.org/wiki/Cron

`
Hash (#)
    '#' is allowed for the day-of-week field, and must be followed by a number between one and five. It allows specifying constructs such as "the second Friday" of a given month.[[19]](https://en.wikipedia.org/wiki/Cron#cite_note-20) For example, entering "5#3" in the day-of-week field corresponds to the third Friday of every month.
`

Right now, this format is not supported. Example to execute a job every 2nd Wednesdays of each month:

```
$ echo "30 0 * * 3#2 job1" | ./croncal.pl
Parsing line 1: invalid range/not a range for field - 3#2 - of type dow, skipping line
```

**Comment by waldner** [comment]
Agreed. I should find out how that plays together with the `/n` modifier, but I'll check it out.

**Comment by waldner** [comment]
I don't have access to a system that supports this syntax, could you provide an example of the semantics (if it's legal at all) of an expression like `1,2,3#2`? Does it mean "the second (monday, tuesday, wednedsay) of the month" or does it mean "all mondays, all tuesdays and the second wednesday of the month"?

**Comment by phibid** [comment]
This cron syntax is for example used in Gitlab which uses fugit (https://github.com/floraison/fugit) to parse the cron syntax.

Those two links https://github.com/floraison/fugit#the-first-monday-of-the-month and https://github.com/floraison/fugit#the-hash-extension, explain the why and the how.

To reply to your questions:

`1,2,3#2`: All the Mondays, all the Tuesdays and the second Wednesday of each month
`1-3#2`: This syntax is not valid. You have to use instead `1#2,2#2,3#2`
`1#2,1#3`: This will express the second and third Monday of each month
`1#2,3`: This will express the second Monday of each month and every Wednesday

So in resume, the hash can only be used after a day of the week. Hash does not support a range. If we want to specify several days, hash included, you have to use the usual coma separated list.

**Comment by waldner** [comment]
Excellent! Let me see what I can come up with.

**Comment by waldner** [comment]
Should be working now. Please try it and report any issues. Thanks!

**Comment by phibid** [comment]
Whoaaa, that was quick. A big thanks !

So now testing the script, I notice that I am unable to display the calendar. Tried on Ubuntu 20.04 and CentOS 7, but nevermind how I am testing it, this command don't display anything:

```
$ echo "30 0 * * 3 job1" | ./croncal.pl
$ 
```

If I try with a wrong formatted entry to stdin:

```
$ echo "dumb test" | ./croncal.pl 
Warning, skipping unrecognized crontab line 1: dumb test
```

Can see the error, so it seems that this is a print issue ?

Is it only me ? Am I doing something wrong here ?

**Comment by phibid** [comment]
Aaaah, ok, just noticed the that the default end is 1 day, sorry.

First tests done, seems promising !!

**Comment by waldner** [comment]
Closing as I'm assuming that it's working fine for you. Feel free to reopen or add further comments of not.

**Comment by phibid** [comment]
Sorry for the late reply. I have implemented this new version, and so far so good, working like a charm it seems.

Thanks for your support !
